version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  ios: ./build/ios/Taskfile.yml
  android: ./build/android/Taskfile.yml

vars:
  APP_NAME: "querybox"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  setup:docker:
    summary: Builds Docker image for cross-compilation (~800MB download)
    cmds:
      - task: common:setup:docker

  build:server:
    summary: Builds the application in server mode (no GUI, HTTP server only)
    cmds:
      - task: common:build:server

  run:server:
    summary: Runs the application in server mode
    cmds:
      - task: common:run:server

  build:docker:
    summary: Builds a Docker image for server mode deployment
    cmds:
      - task: common:build:docker

  run:docker:
    summary: Builds and runs the Docker image
    cmds:
      - task: common:run:docker

  build:plugins:
    summary: Builds all executables in `plugins/` and places them in `bin/plugins`
    cmds:
      - mkdir -p {{.BIN_DIR}}/plugins
      - bash ./scripts/build-plugins.sh

  proto:generate:
    summary: Generate Go code from proto files (requires protoc + plugins)
    cmds:
      - mkdir -p rpc
      - protoc --go_out=rpc --go_opt=paths=source_relative contracts/plugin/v1/plugin.proto || true
      - protoc --go-grpc_out=rpc --go-grpc_opt=paths=source_relative contracts/plugin/v1/plugin.proto || true
      - echo "(If you need exact generated files, install protoc + protoc-gen-go + protoc-gen-go-grpc)"
