// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseConnections() {
    return $Call.ByID(2421872468);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowConnections() {
    return $Call.ByID(1778628337);
}
