// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService is the application-facing service that exposes connection
 * management APIs to the frontend. The service now embeds the persistence and
 * credential-storage logic (previously in connection.ConnectionManager). It is
 * safe for concurrent use.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConnection inserts a new connection record and returns it. The
 * provided `credential` (typically the frontend-serialized auth form) is
 * stored in the OS keyring and the DB only keeps the key reference.
 * @param {string} name
 * @param {string} driverType
 * @param {string} credential
 * @returns {$CancellablePromise<$models.Connection>}
 */
export function CreateConnection(name, driverType, credential) {
    return $Call.ByID(3879129233, name, driverType, credential).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteConnection removes a connection by id and attempts to remove the
 * associated secret from the keyring as a best-effort cleanup.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(16750766, id);
}

/**
 * GetConnection retrieves a single connection by id.
 * @param {string} id
 * @returns {$CancellablePromise<$models.Connection>}
 */
export function GetConnection(id) {
    return $Call.ByID(599383695, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCredential retrieves the raw credential blob associated with the
 * connection.  This is used by the frontend when it needs to establish a
 * plugin connection (e.g. building a tree or executing a query). The value was
 * originally supplied when the connection was created and is stored via
 * CredManager.  Returning the credential to the caller is considered a
 * security-sensitive operation, but the frontend already has full access to a
 * saved connection (it can execute arbitrary queries), so this method simply
 * fetches and returns whatever string is stored under the connection's key.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetCredential(id) {
    return $Call.ByID(2539819102, id);
}

/**
 * ListConnections returns all stored connections ordered by creation time
 * (newest first).
 * @returns {$CancellablePromise<$models.Connection[]>}
 */
export function ListConnections() {
    return $Call.ByID(3704832906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetApp injects the Wails application reference so the service can emit
 * log events to the frontend. Call this after application.New returns.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1095751446, app);
}

// Private type creation functions
const $$createType0 = $models.Connection.createFrom;
const $$createType1 = $Create.Array($$createType0);
