// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService is the application-facing service that exposes connection
 * management APIs to the frontend. Methods are intentionally thin wrappers over
 * the lower-level ConnectionManager to keep bindings small and focused.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "./connection/models.js";

/**
 * CreateConnection creates and persists a new connection record.
 * @param {string} name
 * @param {string} driverType
 * @param {string} credential
 * @returns {$CancellablePromise<connection$0.Connection>}
 */
export function CreateConnection(name, driverType, credential) {
    return $Call.ByID(3879129233, name, driverType, credential).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteConnection removes a connection by id.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(16750766, id);
}

/**
 * GetConnection retrieves a single connection by id.
 * @param {string} id
 * @returns {$CancellablePromise<connection$0.Connection>}
 */
export function GetConnection(id) {
    return $Call.ByID(599383695, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListConnections returns all configured connections.
 * @returns {$CancellablePromise<connection$0.Connection[]>}
 */
export function ListConnections() {
    return $Call.ByID(3704832906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = connection$0.Connection.createFrom;
const $$createType1 = $Create.Array($$createType0);
