// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Connection represents a persisted connection record. NOTE: `CredentialKey`
 * stores a key (not the secret) that the CredManager uses to fetch the secret
 * from the OS keyring.
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("driver_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["driver_type"] = "";
        }
        if (!("credential_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_key"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * LogEntry is the payload emitted on the EventAppLog event.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {LogLevel}
             */
            this["level"] = LogLevel.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * RFC3339Nano UTC
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * LogLevel represents the severity of a log entry.
 * @readonly
 * @enum {string}
 */
export const LogLevel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LogLevelInfo: "info",
    LogLevelWarn: "warn",
    LogLevelError: "error",
};
