// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: contracts/plugin/v1/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type defines the category of the plugin, which can be used by the core to determine how to handle it (e.g. render query editor for DRIVER plugins).
type PluginV1_Type int32

const (
	PluginV1_UNKNOWN PluginV1_Type = 0
	PluginV1_DRIVER  PluginV1_Type = 1 // Driver plugin (e.g. SQL databases like MySQL, Postgres)
)

// Enum value maps for PluginV1_Type.
var (
	PluginV1_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DRIVER",
	}
	PluginV1_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"DRIVER":  1,
	}
)

func (x PluginV1_Type) Enum() *PluginV1_Type {
	p := new(PluginV1_Type)
	*p = x
	return p
}

func (x PluginV1_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginV1_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginV1_Type) Type() protoreflect.EnumType {
	return &file_contracts_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PluginV1_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginV1_Type.Descriptor instead.
func (PluginV1_Type) EnumDescriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 0}
}

// NodeType is an optional hint for the frontend icon renderer and lets Go
// code reference well-known node kinds via generated constants instead of
// raw strings.
type PluginV1_NodeType int32

const (
	PluginV1_NODE_TYPE_UNKNOWN    PluginV1_NodeType = 0 // generic / unspecified
	PluginV1_NODE_TYPE_DATABASE   PluginV1_NodeType = 1
	PluginV1_NODE_TYPE_TABLE      PluginV1_NodeType = 2
	PluginV1_NODE_TYPE_COLUMN     PluginV1_NodeType = 3
	PluginV1_NODE_TYPE_SCHEMA     PluginV1_NodeType = 4
	PluginV1_NODE_TYPE_VIEW       PluginV1_NodeType = 5
	PluginV1_NODE_TYPE_ACTION     PluginV1_NodeType = 6 // indicates a leaf node that represents an action, not a database object
	PluginV1_NODE_TYPE_COLLECTION PluginV1_NodeType = 7 // for document stores like Mongo
	PluginV1_NODE_TYPE_KEY        PluginV1_NodeType = 8 // for key/value stores like Redis
)

// Enum value maps for PluginV1_NodeType.
var (
	PluginV1_NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNKNOWN",
		1: "NODE_TYPE_DATABASE",
		2: "NODE_TYPE_TABLE",
		3: "NODE_TYPE_COLUMN",
		4: "NODE_TYPE_SCHEMA",
		5: "NODE_TYPE_VIEW",
		6: "NODE_TYPE_ACTION",
		7: "NODE_TYPE_COLLECTION",
		8: "NODE_TYPE_KEY",
	}
	PluginV1_NodeType_value = map[string]int32{
		"NODE_TYPE_UNKNOWN":    0,
		"NODE_TYPE_DATABASE":   1,
		"NODE_TYPE_TABLE":      2,
		"NODE_TYPE_COLUMN":     3,
		"NODE_TYPE_SCHEMA":     4,
		"NODE_TYPE_VIEW":       5,
		"NODE_TYPE_ACTION":     6,
		"NODE_TYPE_COLLECTION": 7,
		"NODE_TYPE_KEY":        8,
	}
)

func (x PluginV1_NodeType) Enum() *PluginV1_NodeType {
	p := new(PluginV1_NodeType)
	*p = x
	return p
}

func (x PluginV1_NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginV1_NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (PluginV1_NodeType) Type() protoreflect.EnumType {
	return &file_contracts_plugin_v1_plugin_proto_enumTypes[1]
}

func (x PluginV1_NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginV1_NodeType.Descriptor instead.
func (PluginV1_NodeType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 1}
}

// FieldType defines the type of input field to render for authentication details.
type PluginV1_AuthField_FieldType int32

const (
	PluginV1_AuthField_FIELD_UNKNOWN PluginV1_AuthField_FieldType = 0
	PluginV1_AuthField_TEXT          PluginV1_AuthField_FieldType = 1
	PluginV1_AuthField_NUMBER        PluginV1_AuthField_FieldType = 2
	PluginV1_AuthField_PASSWORD      PluginV1_AuthField_FieldType = 3
	PluginV1_AuthField_CHECKBOX      PluginV1_AuthField_FieldType = 4
	PluginV1_AuthField_SELECT        PluginV1_AuthField_FieldType = 5
	PluginV1_AuthField_FILE_PATH     PluginV1_AuthField_FieldType = 6
)

// Enum value maps for PluginV1_AuthField_FieldType.
var (
	PluginV1_AuthField_FieldType_name = map[int32]string{
		0: "FIELD_UNKNOWN",
		1: "TEXT",
		2: "NUMBER",
		3: "PASSWORD",
		4: "CHECKBOX",
		5: "SELECT",
		6: "FILE_PATH",
	}
	PluginV1_AuthField_FieldType_value = map[string]int32{
		"FIELD_UNKNOWN": 0,
		"TEXT":          1,
		"NUMBER":        2,
		"PASSWORD":      3,
		"CHECKBOX":      4,
		"SELECT":        5,
		"FILE_PATH":     6,
	}
)

func (x PluginV1_AuthField_FieldType) Enum() *PluginV1_AuthField_FieldType {
	p := new(PluginV1_AuthField_FieldType)
	*p = x
	return p
}

func (x PluginV1_AuthField_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginV1_AuthField_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (PluginV1_AuthField_FieldType) Type() protoreflect.EnumType {
	return &file_contracts_plugin_v1_plugin_proto_enumTypes[2]
}

func (x PluginV1_AuthField_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginV1_AuthField_FieldType.Descriptor instead.
func (PluginV1_AuthField_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 10, 0}
}

// PluginV1 defines the data structures for plugin information, execution, and authentication forms.
type PluginV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1) Reset() {
	*x = PluginV1{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1) ProtoMessage() {}

func (x *PluginV1) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1.ProtoReflect.Descriptor instead.
func (*PluginV1) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginV1_InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_InfoRequest) Reset() {
	*x = PluginV1_InfoRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_InfoRequest) ProtoMessage() {}

func (x *PluginV1_InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_InfoRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_InfoRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type PluginV1_InfoResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Type        PluginV1_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.PluginV1_Type" json:"type,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Optional fields for richer metadata.  Older clients will ignore these
	// without issue; plugins may populate any subset.
	Url    string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`       // homepage, docs, repo, etc.
	Author string `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"` // maintainer or organization name
	// Free-form maps for extensibility.  Both are string to
	// string for simplicity; plugins can embed JSON in values if needed.
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary plugin-specific info
	Settings map[string]string `protobuf:"bytes,8,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // hints the core can use (defaults, etc.)
	// Common use‑cases that a core might care about.
	Capabilities  []string `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`       // e.g. "transactions","ssl"
	Tags          []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`                      // categories/statistics
	License       string   `protobuf:"bytes,11,opt,name=license,proto3" json:"license,omitempty"`                // SPDX identifier or text
	IconUrl       string   `protobuf:"bytes,12,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"` // link to a small icon
	Contact       string   `protobuf:"bytes,13,opt,name=contact,proto3" json:"contact,omitempty"`                // maintainer email/URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_InfoResponse) Reset() {
	*x = PluginV1_InfoResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_InfoResponse) ProtoMessage() {}

func (x *PluginV1_InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_InfoResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_InfoResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PluginV1_InfoResponse) GetType() PluginV1_Type {
	if x != nil {
		return x.Type
	}
	return PluginV1_UNKNOWN
}

func (x *PluginV1_InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PluginV1_InfoResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PluginV1_InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginV1_InfoResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginV1_InfoResponse) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type PluginV1_ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection is plugin-defined key/value (host, user, password, ...)
	Connection    map[string]string `protobuf:"bytes,1,rep,name=connection,proto3" json:"connection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Query         string            `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // Query or plugin-specific payload (SQL/NoSQL/etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ExecRequest) Reset() {
	*x = PluginV1_ExecRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ExecRequest) ProtoMessage() {}

func (x *PluginV1_ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ExecRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_ExecRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PluginV1_ExecRequest) GetConnection() map[string]string {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *PluginV1_ExecRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// ExecResponse contains the output of an Exec call,
// provide a typed, extensible envelope that can represent at least three
// common data models (SQL, document/JSON, and simple key-value maps).  The
// UI will examine the oneof field and render accordingly instead of relying
// on plugin-specific semantics.
type PluginV1_ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PluginV1_ExecResult   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // optional error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ExecResponse) Reset() {
	*x = PluginV1_ExecResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ExecResponse) ProtoMessage() {}

func (x *PluginV1_ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ExecResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_ExecResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PluginV1_ExecResponse) GetResult() *PluginV1_ExecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PluginV1_ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecResult is a wrapper around the various result types supported by a
// plugin.  Only one field will be populated.
type PluginV1_ExecResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginV1_ExecResult_Sql
	//	*PluginV1_ExecResult_Document
	//	*PluginV1_ExecResult_Kv
	Payload       isPluginV1_ExecResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ExecResult) Reset() {
	*x = PluginV1_ExecResult{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ExecResult) ProtoMessage() {}

func (x *PluginV1_ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ExecResult.ProtoReflect.Descriptor instead.
func (*PluginV1_ExecResult) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 4}
}

func (x *PluginV1_ExecResult) GetPayload() isPluginV1_ExecResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginV1_ExecResult) GetSql() *PluginV1_SqlResult {
	if x != nil {
		if x, ok := x.Payload.(*PluginV1_ExecResult_Sql); ok {
			return x.Sql
		}
	}
	return nil
}

func (x *PluginV1_ExecResult) GetDocument() *PluginV1_DocumentResult {
	if x != nil {
		if x, ok := x.Payload.(*PluginV1_ExecResult_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *PluginV1_ExecResult) GetKv() *PluginV1_KeyValueResult {
	if x != nil {
		if x, ok := x.Payload.(*PluginV1_ExecResult_Kv); ok {
			return x.Kv
		}
	}
	return nil
}

type isPluginV1_ExecResult_Payload interface {
	isPluginV1_ExecResult_Payload()
}

type PluginV1_ExecResult_Sql struct {
	Sql *PluginV1_SqlResult `protobuf:"bytes,1,opt,name=sql,proto3,oneof"`
}

type PluginV1_ExecResult_Document struct {
	Document *PluginV1_DocumentResult `protobuf:"bytes,2,opt,name=document,proto3,oneof"`
}

type PluginV1_ExecResult_Kv struct {
	Kv *PluginV1_KeyValueResult `protobuf:"bytes,3,opt,name=kv,proto3,oneof"`
}

func (*PluginV1_ExecResult_Sql) isPluginV1_ExecResult_Payload() {}

func (*PluginV1_ExecResult_Document) isPluginV1_ExecResult_Payload() {}

func (*PluginV1_ExecResult_Kv) isPluginV1_ExecResult_Payload() {}

// SqlResult describes a tabular result set with explicit columns and rows.
// All values are serialized as strings; plugins are free to format them as
// they wish (e.g. quoting) but the UI will treat them generically.
// Columns carry metadata about each field in a tabular SQL result.  Name is
// required; type is optional and may reflect the database's type name (e.g.
// "varchar", "int").  The UI can use this information to choose appropriate
// input/edit controls when presenting results or constructing inserts.
type PluginV1_Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_Column) Reset() {
	*x = PluginV1_Column{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_Column) ProtoMessage() {}

func (x *PluginV1_Column) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_Column.ProtoReflect.Descriptor instead.
func (*PluginV1_Column) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 5}
}

func (x *PluginV1_Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginV1_Column) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PluginV1_SqlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*PluginV1_Column     `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*PluginV1_Row        `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_SqlResult) Reset() {
	*x = PluginV1_SqlResult{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_SqlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_SqlResult) ProtoMessage() {}

func (x *PluginV1_SqlResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_SqlResult.ProtoReflect.Descriptor instead.
func (*PluginV1_SqlResult) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 6}
}

func (x *PluginV1_SqlResult) GetColumns() []*PluginV1_Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *PluginV1_SqlResult) GetRows() []*PluginV1_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type PluginV1_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_Row) Reset() {
	*x = PluginV1_Row{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_Row) ProtoMessage() {}

func (x *PluginV1_Row) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_Row.ProtoReflect.Descriptor instead.
func (*PluginV1_Row) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 7}
}

func (x *PluginV1_Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// DocumentResult is intended for document‑oriented databases (Mongo, Couch,
// etc.) where each entry is an object.  The google.protobuf.Struct type is
// used here to avoid prescribing a schema – it maps cleanly to JS objects
// and the frontend can iterate the fields dynamically.
type PluginV1_DocumentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*structpb.Struct     `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_DocumentResult) Reset() {
	*x = PluginV1_DocumentResult{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_DocumentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_DocumentResult) ProtoMessage() {}

func (x *PluginV1_DocumentResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_DocumentResult.ProtoReflect.Descriptor instead.
func (*PluginV1_DocumentResult) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 8}
}

func (x *PluginV1_DocumentResult) GetDocuments() []*structpb.Struct {
	if x != nil {
		return x.Documents
	}
	return nil
}

// KeyValueResult is a simple map of string→string appropriate for things like
// Redis or other key/value stores where the “row” concept isn’t meaningful.
type PluginV1_KeyValueResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_KeyValueResult) Reset() {
	*x = PluginV1_KeyValueResult{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_KeyValueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_KeyValueResult) ProtoMessage() {}

func (x *PluginV1_KeyValueResult) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_KeyValueResult.ProtoReflect.Descriptor instead.
func (*PluginV1_KeyValueResult) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 9}
}

func (x *PluginV1_KeyValueResult) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// AuthField represents a single input field for authentication (e.g. host, user, password).
// The plugin defines the fields it needs for authentication and the core renders them accordingly.
type PluginV1_AuthField struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          PluginV1_AuthField_FieldType `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.PluginV1_AuthField_FieldType" json:"type,omitempty"` // input type
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // machine name (lower-case, no spaces)
	Label         string                       `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`                                            // human-friendly label
	Value         string                       `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                                            // default/value used when invoking plugin
	Required      bool                         `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`                                     // whether field is required
	Options       []string                     `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`                                        // for select inputs
	Placeholder   string                       `protobuf:"bytes,7,opt,name=placeholder,proto3" json:"placeholder,omitempty"`                                // optional placeholder
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_AuthField) Reset() {
	*x = PluginV1_AuthField{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_AuthField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_AuthField) ProtoMessage() {}

func (x *PluginV1_AuthField) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_AuthField.ProtoReflect.Descriptor instead.
func (*PluginV1_AuthField) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 10}
}

func (x *PluginV1_AuthField) GetType() PluginV1_AuthField_FieldType {
	if x != nil {
		return x.Type
	}
	return PluginV1_AuthField_FIELD_UNKNOWN
}

func (x *PluginV1_AuthField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginV1_AuthField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PluginV1_AuthField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PluginV1_AuthField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *PluginV1_AuthField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PluginV1_AuthField) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// AuthForm represents a set of fields for a specific authentication method (e.g. "basic", "oauth").
// The core will render a tab per form and present the `fields` to the user. When the user submits
// the form, the core will send the field values back to the plugin for connection/authentication.
type PluginV1_AuthForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`   // e.g. "basic"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "Basic"
	Fields        []*PluginV1_AuthField  `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_AuthForm) Reset() {
	*x = PluginV1_AuthForm{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_AuthForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_AuthForm) ProtoMessage() {}

func (x *PluginV1_AuthForm) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_AuthForm.ProtoReflect.Descriptor instead.
func (*PluginV1_AuthForm) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 11}
}

func (x *PluginV1_AuthForm) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PluginV1_AuthForm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginV1_AuthForm) GetFields() []*PluginV1_AuthField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PluginV1_AuthFormsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_AuthFormsRequest) Reset() {
	*x = PluginV1_AuthFormsRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_AuthFormsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_AuthFormsRequest) ProtoMessage() {}

func (x *PluginV1_AuthFormsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_AuthFormsRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_AuthFormsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 12}
}

type PluginV1_AuthFormsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// map key is the form `key` (e.g. "basic").
	Forms         map[string]*PluginV1_AuthForm `protobuf:"bytes,1,rep,name=forms,proto3" json:"forms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_AuthFormsResponse) Reset() {
	*x = PluginV1_AuthFormsResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_AuthFormsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_AuthFormsResponse) ProtoMessage() {}

func (x *PluginV1_AuthFormsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_AuthFormsResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_AuthFormsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 13}
}

func (x *PluginV1_AuthFormsResponse) GetForms() map[string]*PluginV1_AuthForm {
	if x != nil {
		return x.Forms
	}
	return nil
}

// ConnectionTreeRequest is sent when the frontend wants to browse a
// connection.  The contents are purely driver-defined.
type PluginV1_ConnectionTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    map[string]string      `protobuf:"bytes,1,rep,name=connection,proto3" json:"connection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ConnectionTreeRequest) Reset() {
	*x = PluginV1_ConnectionTreeRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ConnectionTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ConnectionTreeRequest) ProtoMessage() {}

func (x *PluginV1_ConnectionTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ConnectionTreeRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_ConnectionTreeRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 14}
}

func (x *PluginV1_ConnectionTreeRequest) GetConnection() map[string]string {
	if x != nil {
		return x.Connection
	}
	return nil
}

type PluginV1_ConnectionTreeResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Nodes         []*PluginV1_ConnectionTreeNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ConnectionTreeResponse) Reset() {
	*x = PluginV1_ConnectionTreeResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ConnectionTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ConnectionTreeResponse) ProtoMessage() {}

func (x *PluginV1_ConnectionTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ConnectionTreeResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_ConnectionTreeResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 15}
}

func (x *PluginV1_ConnectionTreeResponse) GetNodes() []*PluginV1_ConnectionTreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PluginV1_ConnectionTreeNode struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Key           string                           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // unique within the returned tree
	Label         string                           `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // user-visible text
	Children      []*PluginV1_ConnectionTreeNode   `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Actions       []*PluginV1_ConnectionTreeAction `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	NodeType      PluginV1_NodeType                `protobuf:"varint,5,opt,name=node_type,json=nodeType,proto3,enum=plugin.v1.PluginV1_NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ConnectionTreeNode) Reset() {
	*x = PluginV1_ConnectionTreeNode{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ConnectionTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ConnectionTreeNode) ProtoMessage() {}

func (x *PluginV1_ConnectionTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ConnectionTreeNode.ProtoReflect.Descriptor instead.
func (*PluginV1_ConnectionTreeNode) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 16}
}

func (x *PluginV1_ConnectionTreeNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PluginV1_ConnectionTreeNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PluginV1_ConnectionTreeNode) GetChildren() []*PluginV1_ConnectionTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *PluginV1_ConnectionTreeNode) GetActions() []*PluginV1_ConnectionTreeAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PluginV1_ConnectionTreeNode) GetNodeType() PluginV1_NodeType {
	if x != nil {
		return x.NodeType
	}
	return PluginV1_NODE_TYPE_UNKNOWN
}

type PluginV1_ConnectionTreeAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`   // machine name (e.g. "select", "describe")
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // displayed in a context menu or double-click
	Query string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // plugin-interpreted payload (often SQL)
	// hidden suppresses the action from the context menu / action buttons.
	// Use this for actions that should only fire on leaf-node click, not be
	// explicitly listed as selectable options.
	Hidden        bool `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	NewTab        bool `protobuf:"varint,5,opt,name=new_tab,json=newTab,proto3" json:"new_tab,omitempty"` // whether the core should open a new tab when this action is executed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ConnectionTreeAction) Reset() {
	*x = PluginV1_ConnectionTreeAction{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ConnectionTreeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ConnectionTreeAction) ProtoMessage() {}

func (x *PluginV1_ConnectionTreeAction) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ConnectionTreeAction.ProtoReflect.Descriptor instead.
func (*PluginV1_ConnectionTreeAction) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 17}
}

func (x *PluginV1_ConnectionTreeAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginV1_ConnectionTreeAction) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PluginV1_ConnectionTreeAction) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PluginV1_ConnectionTreeAction) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *PluginV1_ConnectionTreeAction) GetNewTab() bool {
	if x != nil {
		return x.NewTab
	}
	return false
}

// TestConnectionRequest carries the same credential map as ExecRequest so
// plugins can reuse their existing connection-building logic.
type PluginV1_TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    map[string]string      `protobuf:"bytes,1,rep,name=connection,proto3" json:"connection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_TestConnectionRequest) Reset() {
	*x = PluginV1_TestConnectionRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_TestConnectionRequest) ProtoMessage() {}

func (x *PluginV1_TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 18}
}

func (x *PluginV1_TestConnectionRequest) GetConnection() map[string]string {
	if x != nil {
		return x.Connection
	}
	return nil
}

// TestConnectionResponse indicates whether the connection attempt succeeded.
// ok=true means the plugin could open and ping the data store.
// message carries a human-readable success or failure description.
type PluginV1_TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_TestConnectionResponse) Reset() {
	*x = PluginV1_TestConnectionResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_TestConnectionResponse) ProtoMessage() {}

func (x *PluginV1_TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 19}
}

func (x *PluginV1_TestConnectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PluginV1_TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_contracts_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" contracts/plugin/v1/plugin.proto\x12\tplugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe4\x19\n" +
	"\bPluginV1\x1a\r\n" +
	"\vInfoRequest\x1a\xcf\x04\n" +
	"\fInfoResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.plugin.v1.PluginV1.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12J\n" +
	"\bmetadata\x18\a \x03(\v2..plugin.v1.PluginV1.InfoResponse.MetadataEntryR\bmetadata\x12J\n" +
	"\bsettings\x18\b \x03(\v2..plugin.v1.PluginV1.InfoResponse.SettingsEntryR\bsettings\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x18\n" +
	"\alicense\x18\v \x01(\tR\alicense\x12\x19\n" +
	"\bicon_url\x18\f \x01(\tR\aiconUrl\x12\x18\n" +
	"\acontact\x18\r \x01(\tR\acontact\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xb3\x01\n" +
	"\vExecRequest\x12O\n" +
	"\n" +
	"connection\x18\x01 \x03(\v2/.plugin.v1.PluginV1.ExecRequest.ConnectionEntryR\n" +
	"connection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x1a=\n" +
	"\x0fConnectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\\\n" +
	"\fExecResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.plugin.v1.PluginV1.ExecResultR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a\xc2\x01\n" +
	"\n" +
	"ExecResult\x121\n" +
	"\x03sql\x18\x01 \x01(\v2\x1d.plugin.v1.PluginV1.SqlResultH\x00R\x03sql\x12@\n" +
	"\bdocument\x18\x02 \x01(\v2\".plugin.v1.PluginV1.DocumentResultH\x00R\bdocument\x124\n" +
	"\x02kv\x18\x03 \x01(\v2\".plugin.v1.PluginV1.KeyValueResultH\x00R\x02kvB\t\n" +
	"\apayload\x1a0\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x1an\n" +
	"\tSqlResult\x124\n" +
	"\acolumns\x18\x01 \x03(\v2\x1a.plugin.v1.PluginV1.ColumnR\acolumns\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.plugin.v1.PluginV1.RowR\x04rows\x1a\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1aG\n" +
	"\x0eDocumentResult\x125\n" +
	"\tdocuments\x18\x01 \x03(\v2\x17.google.protobuf.StructR\tdocuments\x1a\x8b\x01\n" +
	"\x0eKeyValueResult\x12@\n" +
	"\x04data\x18\x01 \x03(\v2,.plugin.v1.PluginV1.KeyValueResult.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xcd\x02\n" +
	"\tAuthField\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.plugin.v1.PluginV1.AuthField.FieldTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptions\x12 \n" +
	"\vplaceholder\x18\a \x01(\tR\vplaceholder\"k\n" +
	"\tFieldType\x12\x11\n" +
	"\rFIELD_UNKNOWN\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x02\x12\f\n" +
	"\bPASSWORD\x10\x03\x12\f\n" +
	"\bCHECKBOX\x10\x04\x12\n" +
	"\n" +
	"\x06SELECT\x10\x05\x12\r\n" +
	"\tFILE_PATH\x10\x06\x1ag\n" +
	"\bAuthForm\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x06fields\x18\x03 \x03(\v2\x1d.plugin.v1.PluginV1.AuthFieldR\x06fields\x1a\x12\n" +
	"\x10AuthFormsRequest\x1a\xb3\x01\n" +
	"\x11AuthFormsResponse\x12F\n" +
	"\x05forms\x18\x01 \x03(\v20.plugin.v1.PluginV1.AuthFormsResponse.FormsEntryR\x05forms\x1aV\n" +
	"\n" +
	"FormsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.plugin.v1.PluginV1.AuthFormR\x05value:\x028\x01\x1a\xb1\x01\n" +
	"\x15ConnectionTreeRequest\x12Y\n" +
	"\n" +
	"connection\x18\x01 \x03(\v29.plugin.v1.PluginV1.ConnectionTreeRequest.ConnectionEntryR\n" +
	"connection\x1a=\n" +
	"\x0fConnectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aV\n" +
	"\x16ConnectionTreeResponse\x12<\n" +
	"\x05nodes\x18\x01 \x03(\v2&.plugin.v1.PluginV1.ConnectionTreeNodeR\x05nodes\x1a\xff\x01\n" +
	"\x12ConnectionTreeNode\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12B\n" +
	"\bchildren\x18\x03 \x03(\v2&.plugin.v1.PluginV1.ConnectionTreeNodeR\bchildren\x12B\n" +
	"\aactions\x18\x04 \x03(\v2(.plugin.v1.PluginV1.ConnectionTreeActionR\aactions\x129\n" +
	"\tnode_type\x18\x05 \x01(\x0e2\x1c.plugin.v1.PluginV1.NodeTypeR\bnodeType\x1a\x87\x01\n" +
	"\x14ConnectionTreeAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12\x17\n" +
	"\anew_tab\x18\x05 \x01(\bR\x06newTab\x1a\xb1\x01\n" +
	"\x15TestConnectionRequest\x12Y\n" +
	"\n" +
	"connection\x18\x01 \x03(\v29.plugin.v1.PluginV1.TestConnectionRequest.ConnectionEntryR\n" +
	"connection\x1a=\n" +
	"\x0fConnectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x16TestConnectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x01\"\xd1\x01\n" +
	"\bNodeType\x12\x15\n" +
	"\x11NODE_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12NODE_TYPE_DATABASE\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_TABLE\x10\x02\x12\x14\n" +
	"\x10NODE_TYPE_COLUMN\x10\x03\x12\x14\n" +
	"\x10NODE_TYPE_SCHEMA\x10\x04\x12\x12\n" +
	"\x0eNODE_TYPE_VIEW\x10\x05\x12\x14\n" +
	"\x10NODE_TYPE_ACTION\x10\x06\x12\x18\n" +
	"\x14NODE_TYPE_COLLECTION\x10\a\x12\x11\n" +
	"\rNODE_TYPE_KEY\x10\b2\xd1\x03\n" +
	"\rPluginService\x12I\n" +
	"\x04Info\x12\x1f.plugin.v1.PluginV1.InfoRequest\x1a .plugin.v1.PluginV1.InfoResponse\x12I\n" +
	"\x04Exec\x12\x1f.plugin.v1.PluginV1.ExecRequest\x1a .plugin.v1.PluginV1.ExecResponse\x12X\n" +
	"\tAuthForms\x12$.plugin.v1.PluginV1.AuthFormsRequest\x1a%.plugin.v1.PluginV1.AuthFormsResponse\x12g\n" +
	"\x0eConnectionTree\x12).plugin.v1.PluginV1.ConnectionTreeRequest\x1a*.plugin.v1.PluginV1.ConnectionTreeResponse\x12g\n" +
	"\x0eTestConnection\x12).plugin.v1.PluginV1.TestConnectionRequest\x1a*.plugin.v1.PluginV1.TestConnectionResponseB\x14Z\x12plugin/v1;pluginpbb\x06proto3"

var (
	file_contracts_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_contracts_plugin_v1_plugin_proto_rawDescData []byte
)

func file_contracts_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_contracts_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_contracts_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_contracts_plugin_v1_plugin_proto_rawDescData
}

var file_contracts_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_contracts_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_contracts_plugin_v1_plugin_proto_goTypes = []any{
	(PluginV1_Type)(0),                      // 0: plugin.v1.PluginV1.Type
	(PluginV1_NodeType)(0),                  // 1: plugin.v1.PluginV1.NodeType
	(PluginV1_AuthField_FieldType)(0),       // 2: plugin.v1.PluginV1.AuthField.FieldType
	(*PluginV1)(nil),                        // 3: plugin.v1.PluginV1
	(*PluginV1_InfoRequest)(nil),            // 4: plugin.v1.PluginV1.InfoRequest
	(*PluginV1_InfoResponse)(nil),           // 5: plugin.v1.PluginV1.InfoResponse
	(*PluginV1_ExecRequest)(nil),            // 6: plugin.v1.PluginV1.ExecRequest
	(*PluginV1_ExecResponse)(nil),           // 7: plugin.v1.PluginV1.ExecResponse
	(*PluginV1_ExecResult)(nil),             // 8: plugin.v1.PluginV1.ExecResult
	(*PluginV1_Column)(nil),                 // 9: plugin.v1.PluginV1.Column
	(*PluginV1_SqlResult)(nil),              // 10: plugin.v1.PluginV1.SqlResult
	(*PluginV1_Row)(nil),                    // 11: plugin.v1.PluginV1.Row
	(*PluginV1_DocumentResult)(nil),         // 12: plugin.v1.PluginV1.DocumentResult
	(*PluginV1_KeyValueResult)(nil),         // 13: plugin.v1.PluginV1.KeyValueResult
	(*PluginV1_AuthField)(nil),              // 14: plugin.v1.PluginV1.AuthField
	(*PluginV1_AuthForm)(nil),               // 15: plugin.v1.PluginV1.AuthForm
	(*PluginV1_AuthFormsRequest)(nil),       // 16: plugin.v1.PluginV1.AuthFormsRequest
	(*PluginV1_AuthFormsResponse)(nil),      // 17: plugin.v1.PluginV1.AuthFormsResponse
	(*PluginV1_ConnectionTreeRequest)(nil),  // 18: plugin.v1.PluginV1.ConnectionTreeRequest
	(*PluginV1_ConnectionTreeResponse)(nil), // 19: plugin.v1.PluginV1.ConnectionTreeResponse
	(*PluginV1_ConnectionTreeNode)(nil),     // 20: plugin.v1.PluginV1.ConnectionTreeNode
	(*PluginV1_ConnectionTreeAction)(nil),   // 21: plugin.v1.PluginV1.ConnectionTreeAction
	(*PluginV1_TestConnectionRequest)(nil),  // 22: plugin.v1.PluginV1.TestConnectionRequest
	(*PluginV1_TestConnectionResponse)(nil), // 23: plugin.v1.PluginV1.TestConnectionResponse
	nil,                                     // 24: plugin.v1.PluginV1.InfoResponse.MetadataEntry
	nil,                                     // 25: plugin.v1.PluginV1.InfoResponse.SettingsEntry
	nil,                                     // 26: plugin.v1.PluginV1.ExecRequest.ConnectionEntry
	nil,                                     // 27: plugin.v1.PluginV1.KeyValueResult.DataEntry
	nil,                                     // 28: plugin.v1.PluginV1.AuthFormsResponse.FormsEntry
	nil,                                     // 29: plugin.v1.PluginV1.ConnectionTreeRequest.ConnectionEntry
	nil,                                     // 30: plugin.v1.PluginV1.TestConnectionRequest.ConnectionEntry
	(*structpb.Struct)(nil),                 // 31: google.protobuf.Struct
}
var file_contracts_plugin_v1_plugin_proto_depIdxs = []int32{
	0,  // 0: plugin.v1.PluginV1.InfoResponse.type:type_name -> plugin.v1.PluginV1.Type
	24, // 1: plugin.v1.PluginV1.InfoResponse.metadata:type_name -> plugin.v1.PluginV1.InfoResponse.MetadataEntry
	25, // 2: plugin.v1.PluginV1.InfoResponse.settings:type_name -> plugin.v1.PluginV1.InfoResponse.SettingsEntry
	26, // 3: plugin.v1.PluginV1.ExecRequest.connection:type_name -> plugin.v1.PluginV1.ExecRequest.ConnectionEntry
	8,  // 4: plugin.v1.PluginV1.ExecResponse.result:type_name -> plugin.v1.PluginV1.ExecResult
	10, // 5: plugin.v1.PluginV1.ExecResult.sql:type_name -> plugin.v1.PluginV1.SqlResult
	12, // 6: plugin.v1.PluginV1.ExecResult.document:type_name -> plugin.v1.PluginV1.DocumentResult
	13, // 7: plugin.v1.PluginV1.ExecResult.kv:type_name -> plugin.v1.PluginV1.KeyValueResult
	9,  // 8: plugin.v1.PluginV1.SqlResult.columns:type_name -> plugin.v1.PluginV1.Column
	11, // 9: plugin.v1.PluginV1.SqlResult.rows:type_name -> plugin.v1.PluginV1.Row
	31, // 10: plugin.v1.PluginV1.DocumentResult.documents:type_name -> google.protobuf.Struct
	27, // 11: plugin.v1.PluginV1.KeyValueResult.data:type_name -> plugin.v1.PluginV1.KeyValueResult.DataEntry
	2,  // 12: plugin.v1.PluginV1.AuthField.type:type_name -> plugin.v1.PluginV1.AuthField.FieldType
	14, // 13: plugin.v1.PluginV1.AuthForm.fields:type_name -> plugin.v1.PluginV1.AuthField
	28, // 14: plugin.v1.PluginV1.AuthFormsResponse.forms:type_name -> plugin.v1.PluginV1.AuthFormsResponse.FormsEntry
	29, // 15: plugin.v1.PluginV1.ConnectionTreeRequest.connection:type_name -> plugin.v1.PluginV1.ConnectionTreeRequest.ConnectionEntry
	20, // 16: plugin.v1.PluginV1.ConnectionTreeResponse.nodes:type_name -> plugin.v1.PluginV1.ConnectionTreeNode
	20, // 17: plugin.v1.PluginV1.ConnectionTreeNode.children:type_name -> plugin.v1.PluginV1.ConnectionTreeNode
	21, // 18: plugin.v1.PluginV1.ConnectionTreeNode.actions:type_name -> plugin.v1.PluginV1.ConnectionTreeAction
	1,  // 19: plugin.v1.PluginV1.ConnectionTreeNode.node_type:type_name -> plugin.v1.PluginV1.NodeType
	30, // 20: plugin.v1.PluginV1.TestConnectionRequest.connection:type_name -> plugin.v1.PluginV1.TestConnectionRequest.ConnectionEntry
	15, // 21: plugin.v1.PluginV1.AuthFormsResponse.FormsEntry.value:type_name -> plugin.v1.PluginV1.AuthForm
	4,  // 22: plugin.v1.PluginService.Info:input_type -> plugin.v1.PluginV1.InfoRequest
	6,  // 23: plugin.v1.PluginService.Exec:input_type -> plugin.v1.PluginV1.ExecRequest
	16, // 24: plugin.v1.PluginService.AuthForms:input_type -> plugin.v1.PluginV1.AuthFormsRequest
	18, // 25: plugin.v1.PluginService.ConnectionTree:input_type -> plugin.v1.PluginV1.ConnectionTreeRequest
	22, // 26: plugin.v1.PluginService.TestConnection:input_type -> plugin.v1.PluginV1.TestConnectionRequest
	5,  // 27: plugin.v1.PluginService.Info:output_type -> plugin.v1.PluginV1.InfoResponse
	7,  // 28: plugin.v1.PluginService.Exec:output_type -> plugin.v1.PluginV1.ExecResponse
	17, // 29: plugin.v1.PluginService.AuthForms:output_type -> plugin.v1.PluginV1.AuthFormsResponse
	19, // 30: plugin.v1.PluginService.ConnectionTree:output_type -> plugin.v1.PluginV1.ConnectionTreeResponse
	23, // 31: plugin.v1.PluginService.TestConnection:output_type -> plugin.v1.PluginV1.TestConnectionResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_contracts_plugin_v1_plugin_proto_init() }
func file_contracts_plugin_v1_plugin_proto_init() {
	if File_contracts_plugin_v1_plugin_proto != nil {
		return
	}
	file_contracts_plugin_v1_plugin_proto_msgTypes[5].OneofWrappers = []any{
		(*PluginV1_ExecResult_Sql)(nil),
		(*PluginV1_ExecResult_Document)(nil),
		(*PluginV1_ExecResult_Kv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_contracts_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_contracts_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_contracts_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_contracts_plugin_v1_plugin_proto = out.File
	file_contracts_plugin_v1_plugin_proto_goTypes = nil
	file_contracts_plugin_v1_plugin_proto_depIdxs = nil
}
