// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.6
// source: contracts/plugin/v1/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginV1_Type int32

const (
	PluginV1_UNKNOWN PluginV1_Type = 0
	PluginV1_DRIVER  PluginV1_Type = 1 // SQL plugin (e.g. MySQL, Postgres, etc.)
)

// Enum value maps for PluginV1_Type.
var (
	PluginV1_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DRIVER",
	}
	PluginV1_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"DRIVER":  1,
	}
)

func (x PluginV1_Type) Enum() *PluginV1_Type {
	p := new(PluginV1_Type)
	*p = x
	return p
}

func (x PluginV1_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginV1_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginV1_Type) Type() protoreflect.EnumType {
	return &file_contracts_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PluginV1_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginV1_Type.Descriptor instead.
func (PluginV1_Type) EnumDescriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type PluginV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1) Reset() {
	*x = PluginV1{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1) ProtoMessage() {}

func (x *PluginV1) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1.ProtoReflect.Descriptor instead.
func (*PluginV1) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginV1_InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_InfoRequest) Reset() {
	*x = PluginV1_InfoRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_InfoRequest) ProtoMessage() {}

func (x *PluginV1_InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_InfoRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_InfoRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type PluginV1_InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PluginV1_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.PluginV1_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_InfoResponse) Reset() {
	*x = PluginV1_InfoResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_InfoResponse) ProtoMessage() {}

func (x *PluginV1_InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_InfoResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_InfoResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PluginV1_InfoResponse) GetType() PluginV1_Type {
	if x != nil {
		return x.Type
	}
	return PluginV1_UNKNOWN
}

func (x *PluginV1_InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginV1_InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PluginV1_ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection is plugin-defined key/value (host, user, password, ...)
	Connection    map[string]string `protobuf:"bytes,1,rep,name=connection,proto3" json:"connection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sql           string            `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"` // SQL or plugin-specific payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ExecRequest) Reset() {
	*x = PluginV1_ExecRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ExecRequest) ProtoMessage() {}

func (x *PluginV1_ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ExecRequest.ProtoReflect.Descriptor instead.
func (*PluginV1_ExecRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PluginV1_ExecRequest) GetConnection() map[string]string {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *PluginV1_ExecRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type PluginV1_ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // plugin-serialized result (string/json)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   // optional error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginV1_ExecResponse) Reset() {
	*x = PluginV1_ExecResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginV1_ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginV1_ExecResponse) ProtoMessage() {}

func (x *PluginV1_ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginV1_ExecResponse.ProtoReflect.Descriptor instead.
func (*PluginV1_ExecResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PluginV1_ExecResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PluginV1_ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_contracts_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_contracts_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" contracts/plugin/v1/plugin.proto\x12\tplugin.v1\"\xb9\x03\n" +
	"\bPluginV1\x1a\r\n" +
	"\vInfoRequest\x1a\x8c\x01\n" +
	"\fInfoResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.plugin.v1.PluginV1.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x1a\xaf\x01\n" +
	"\vExecRequest\x12O\n" +
	"\n" +
	"connection\x18\x01 \x03(\v2/.plugin.v1.PluginV1.ExecRequest.ConnectionEntryR\n" +
	"connection\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x1a=\n" +
	"\x0fConnectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1f\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x012\xa5\x01\n" +
	"\rPluginService\x12I\n" +
	"\x04Info\x12\x1f.plugin.v1.PluginV1.InfoRequest\x1a .plugin.v1.PluginV1.InfoResponse\x12I\n" +
	"\x04Exec\x12\x1f.plugin.v1.PluginV1.ExecRequest\x1a .plugin.v1.PluginV1.ExecResponseB\x14Z\x12plugin/v1;pluginpbb\x06proto3"

var (
	file_contracts_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_contracts_plugin_v1_plugin_proto_rawDescData []byte
)

func file_contracts_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_contracts_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_contracts_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_contracts_plugin_v1_plugin_proto_rawDescData
}

var file_contracts_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contracts_plugin_v1_plugin_proto_goTypes = []any{
	(PluginV1_Type)(0),            // 0: plugin.v1.PluginV1.Type
	(*PluginV1)(nil),              // 1: plugin.v1.PluginV1
	(*PluginV1_InfoRequest)(nil),  // 2: plugin.v1.PluginV1.InfoRequest
	(*PluginV1_InfoResponse)(nil), // 3: plugin.v1.PluginV1.InfoResponse
	(*PluginV1_ExecRequest)(nil),  // 4: plugin.v1.PluginV1.ExecRequest
	(*PluginV1_ExecResponse)(nil), // 5: plugin.v1.PluginV1.ExecResponse
	nil,                           // 6: plugin.v1.PluginV1.ExecRequest.ConnectionEntry
}
var file_contracts_plugin_v1_plugin_proto_depIdxs = []int32{
	0, // 0: plugin.v1.PluginV1.InfoResponse.type:type_name -> plugin.v1.PluginV1.Type
	6, // 1: plugin.v1.PluginV1.ExecRequest.connection:type_name -> plugin.v1.PluginV1.ExecRequest.ConnectionEntry
	2, // 2: plugin.v1.PluginService.Info:input_type -> plugin.v1.PluginV1.InfoRequest
	4, // 3: plugin.v1.PluginService.Exec:input_type -> plugin.v1.PluginV1.ExecRequest
	3, // 4: plugin.v1.PluginService.Info:output_type -> plugin.v1.PluginV1.InfoResponse
	5, // 5: plugin.v1.PluginService.Exec:output_type -> plugin.v1.PluginV1.ExecResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_plugin_v1_plugin_proto_init() }
func file_contracts_plugin_v1_plugin_proto_init() {
	if File_contracts_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_contracts_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_contracts_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_contracts_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_contracts_plugin_v1_plugin_proto = out.File
	file_contracts_plugin_v1_plugin_proto_goTypes = nil
	file_contracts_plugin_v1_plugin_proto_depIdxs = nil
}
