// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: contracts/plugin/v1/plugin.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Info_FullMethodName      = "/plugin.v1.PluginService/Info"
	PluginService_Exec_FullMethodName      = "/plugin.v1.PluginService/Exec"
	PluginService_AuthForms_FullMethodName = "/plugin.v1.PluginService/AuthForms"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Contract for on-demand plugins (CLI-invoked). Plugins SHOULD implement
type PluginServiceClient interface {
	// Info returns basic information about the plugin (type, name, version, description).
	Info(ctx context.Context, in *PluginV1_InfoRequest, opts ...grpc.CallOption) (*PluginV1_InfoResponse, error)
	// Exec executes a plugin-specific command (e.g. SQL/NoSQL query) and returns the result.
	// The core will pass user-provided connection details (e.g. host, user, password) and
	// the plugin will handle the execution and return a serialized result (string/json) or an error message.
	Exec(ctx context.Context, in *PluginV1_ExecRequest, opts ...grpc.CallOption) (*PluginV1_ExecResponse, error)
	// AuthForms returns available authentication forms the plugin supports. The core
	// will render these forms (tabs) and send the selected form values back
	// to the plugin when creating a connection.
	AuthForms(ctx context.Context, in *PluginV1_AuthFormsRequest, opts ...grpc.CallOption) (*PluginV1_AuthFormsResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Info(ctx context.Context, in *PluginV1_InfoRequest, opts ...grpc.CallOption) (*PluginV1_InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginV1_InfoResponse)
	err := c.cc.Invoke(ctx, PluginService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Exec(ctx context.Context, in *PluginV1_ExecRequest, opts ...grpc.CallOption) (*PluginV1_ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginV1_ExecResponse)
	err := c.cc.Invoke(ctx, PluginService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) AuthForms(ctx context.Context, in *PluginV1_AuthFormsRequest, opts ...grpc.CallOption) (*PluginV1_AuthFormsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginV1_AuthFormsResponse)
	err := c.cc.Invoke(ctx, PluginService_AuthForms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// Contract for on-demand plugins (CLI-invoked). Plugins SHOULD implement
type PluginServiceServer interface {
	// Info returns basic information about the plugin (type, name, version, description).
	Info(context.Context, *PluginV1_InfoRequest) (*PluginV1_InfoResponse, error)
	// Exec executes a plugin-specific command (e.g. SQL/NoSQL query) and returns the result.
	// The core will pass user-provided connection details (e.g. host, user, password) and
	// the plugin will handle the execution and return a serialized result (string/json) or an error message.
	Exec(context.Context, *PluginV1_ExecRequest) (*PluginV1_ExecResponse, error)
	// AuthForms returns available authentication forms the plugin supports. The core
	// will render these forms (tabs) and send the selected form values back
	// to the plugin when creating a connection.
	AuthForms(context.Context, *PluginV1_AuthFormsRequest) (*PluginV1_AuthFormsResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Info(context.Context, *PluginV1_InfoRequest) (*PluginV1_InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPluginServiceServer) Exec(context.Context, *PluginV1_ExecRequest) (*PluginV1_ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedPluginServiceServer) AuthForms(context.Context, *PluginV1_AuthFormsRequest) (*PluginV1_AuthFormsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthForms not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginV1_InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Info(ctx, req.(*PluginV1_InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginV1_ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Exec(ctx, req.(*PluginV1_ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_AuthForms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginV1_AuthFormsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).AuthForms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_AuthForms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).AuthForms(ctx, req.(*PluginV1_AuthFormsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _PluginService_Info_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _PluginService_Exec_Handler,
		},
		{
			MethodName: "AuthForms",
			Handler:    _PluginService_AuthForms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/plugin/v1/plugin.proto",
}
