// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * PluginEntry holds registry info for a single plugin.
 */
export class PluginEntry {
    /**
     * Creates a new PluginEntry instance.
     * @param {Partial<PluginEntry>} [$$source = {}] - The source object to create the PluginEntry.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginEntry(/** @type {Partial<PluginEntry>} */($$parsedSource));
    }
}

/**
 * UpdateStatus is returned to the frontend and cached to disk.
 */
export class UpdateStatus {
    /**
     * Creates a new UpdateStatus instance.
     * @param {Partial<UpdateStatus>} [$$source = {}] - The source object to create the UpdateStatus.
     */
    constructor($$source = {}) {
        if (!("appUpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["appUpdateAvailable"] = false;
        }
        if (!("appLatestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appLatestVersion"] = "";
        }
        if (!("appCurrentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appCurrentVersion"] = "";
        }
        if (!("appReleaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appReleaseUrl"] = "";
        }
        if (!("pluginRegistry" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: PluginEntry }}
             */
            this["pluginRegistry"] = {};
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateStatus}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pluginRegistry" in $$parsedSource) {
            $$parsedSource["pluginRegistry"] = $$createField4_0($$parsedSource["pluginRegistry"]);
        }
        return new UpdateStatus(/** @type {Partial<UpdateStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PluginEntry.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
