// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Updater is a Wails-bound service that checks for app and plugin updates.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckNow forces an immediate check, bypassing the 24h cache.
 * @returns {$CancellablePromise<$models.UpdateStatus>}
 */
export function CheckNow() {
    return $Call.ByID(3690703441).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetUpdateStatus returns cached update status without blocking.
 * @returns {$CancellablePromise<$models.UpdateStatus>}
 */
export function GetUpdateStatus() {
    return $Call.ByID(1450533912).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3309594790, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateStatus.createFrom;
