// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AuthField represents a single input field for authentication (e.g. host, user, password).
 * The plugin defines the fields it needs for authentication and the core renders them accordingly.
 */
export class PluginV1_AuthField {
    /**
     * Creates a new PluginV1_AuthField instance.
     * @param {Partial<PluginV1_AuthField>} [$$source = {}] - The source object to create the PluginV1_AuthField.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * input type
             * @member
             * @type {PluginV1_AuthField_FieldType | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * machine name (lower-case, no spaces)
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * human-friendly label
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * default/value used when invoking plugin
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * whether field is required
             * @member
             * @type {boolean | undefined}
             */
            this["required"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for select inputs
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * optional placeholder
             * @member
             * @type {string | undefined}
             */
            this["placeholder"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_AuthField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_AuthField}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new PluginV1_AuthField(/** @type {Partial<PluginV1_AuthField>} */($$parsedSource));
    }
}

/**
 * FieldType defines the type of input field to render for authentication details.
 * @readonly
 * @enum {number}
 */
export const PluginV1_AuthField_FieldType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    PluginV1_AuthField_FIELD_UNKNOWN: 0,
    PluginV1_AuthField_TEXT: 1,
    PluginV1_AuthField_NUMBER: 2,
    PluginV1_AuthField_PASSWORD: 3,
    PluginV1_AuthField_CHECKBOX: 4,
    PluginV1_AuthField_SELECT: 5,
};

/**
 * AuthForm represents a set of fields for a specific authentication method (e.g. "basic", "oauth").
 * The core will render a tab per form and present the `fields` to the user. When the user submits
 * the form, the core will send the field values back to the plugin for connection/authentication.
 */
export class PluginV1_AuthForm {
    /**
     * Creates a new PluginV1_AuthForm instance.
     * @param {Partial<PluginV1_AuthForm>} [$$source = {}] - The source object to create the PluginV1_AuthForm.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * e.g. "basic"
             * @member
             * @type {string | undefined}
             */
            this["key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * e.g. "Basic"
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(PluginV1_AuthField | null)[] | undefined}
             */
            this["fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_AuthForm instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_AuthForm}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new PluginV1_AuthForm(/** @type {Partial<PluginV1_AuthForm>} */($$parsedSource));
    }
}

export class PluginV1_ConnectionTreeAction {
    /**
     * Creates a new PluginV1_ConnectionTreeAction instance.
     * @param {Partial<PluginV1_ConnectionTreeAction>} [$$source = {}] - The source object to create the PluginV1_ConnectionTreeAction.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * machine name (e.g. "select", "describe")
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * displayed in a context menu or double-click
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * plugin-interpreted payload (often SQL)
             * @member
             * @type {string | undefined}
             */
            this["query"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_ConnectionTreeAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_ConnectionTreeAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginV1_ConnectionTreeAction(/** @type {Partial<PluginV1_ConnectionTreeAction>} */($$parsedSource));
    }
}

export class PluginV1_ConnectionTreeNode {
    /**
     * Creates a new PluginV1_ConnectionTreeNode instance.
     * @param {Partial<PluginV1_ConnectionTreeNode>} [$$source = {}] - The source object to create the PluginV1_ConnectionTreeNode.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * unique within the returned tree
             * @member
             * @type {string | undefined}
             */
            this["key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * user-visible text
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(PluginV1_ConnectionTreeNode | null)[] | undefined}
             */
            this["children"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(PluginV1_ConnectionTreeAction | null)[] | undefined}
             */
            this["actions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_ConnectionTreeNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_ConnectionTreeNode}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField2_0($$parsedSource["children"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField3_0($$parsedSource["actions"]);
        }
        return new PluginV1_ConnectionTreeNode(/** @type {Partial<PluginV1_ConnectionTreeNode>} */($$parsedSource));
    }
}

export class PluginV1_ConnectionTreeResponse {
    /**
     * Creates a new PluginV1_ConnectionTreeResponse instance.
     * @param {Partial<PluginV1_ConnectionTreeResponse>} [$$source = {}] - The source object to create the PluginV1_ConnectionTreeResponse.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(PluginV1_ConnectionTreeNode | null)[] | undefined}
             */
            this["nodes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_ConnectionTreeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_ConnectionTreeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        return new PluginV1_ConnectionTreeResponse(/** @type {Partial<PluginV1_ConnectionTreeResponse>} */($$parsedSource));
    }
}

/**
 * ExecResponse contains the output of an Exec call,
 * provide a typed, extensible envelope that can represent at least three
 * common data models (SQL, document/JSON, and simple key-value maps).  The
 * UI will examine the oneof field and render accordingly instead of relying
 * on plugin-specific semantics.
 */
export class PluginV1_ExecResponse {
    /**
     * Creates a new PluginV1_ExecResponse instance.
     * @param {Partial<PluginV1_ExecResponse>} [$$source = {}] - The source object to create the PluginV1_ExecResponse.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PluginV1_ExecResult | null | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * optional error message
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_ExecResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_ExecResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new PluginV1_ExecResponse(/** @type {Partial<PluginV1_ExecResponse>} */($$parsedSource));
    }
}

/**
 * ExecResult is a wrapper around the various result types supported by a
 * plugin.  Only one field will be populated.
 */
export class PluginV1_ExecResult {
    /**
     * Creates a new PluginV1_ExecResult instance.
     * @param {Partial<PluginV1_ExecResult>} [$$source = {}] - The source object to create the PluginV1_ExecResult.
     */
    constructor($$source = {}) {
        if (!("Payload" in $$source)) {
            /**
             * Types that are valid to be assigned to Payload:
             * 
             * 	*PluginV1_ExecResult_Sql
             * 	*PluginV1_ExecResult_Document
             * 	*PluginV1_ExecResult_Kv
             * @member
             * @type {isPluginV1_ExecResult_Payload}
             */
            this["Payload"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginV1_ExecResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginV1_ExecResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginV1_ExecResult(/** @type {Partial<PluginV1_ExecResult>} */($$parsedSource));
    }
}

/**
 * @typedef {any} isPluginV1_ExecResult_Payload
 */

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PluginV1_AuthField.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PluginV1_ConnectionTreeNode.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = PluginV1_ConnectionTreeAction.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PluginV1_ExecResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
