// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Manager discovers executables under ./bin/plugins and invokes them on-demand.
 * It does NOT manage long-running plugin processes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(2618184216, name);
}

/**
 * EnablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3573057673, name);
}

/**
 * ExecPlugin runs the named plugin with the provided connection info and SQL.
 * The plugin is invoked as an executable: `plugin exec` and receives a JSON
 * payload on stdin. The method returns the plugin's result or an error.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} sql
 * @returns {$CancellablePromise<string>}
 */
export function ExecPlugin(name, connection, sql) {
    return $Call.ByID(2332402495, name, connection, sql);
}

/**
 * ListPlugins returns the discovered plugins (does not start them).
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(668942975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Rescan triggers an immediate directory scan.
 * @returns {$CancellablePromise<void>}
 */
export function Rescan() {
    return $Call.ByID(3306130489);
}

/**
 * Shutdown stops background scanning.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(976093531);
}

// Private type creation functions
const $$createType0 = $models.PluginInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
