// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Manager discovers executables under ./bin/plugins and invokes them on-demand.
 * It does NOT manage long-running plugin processes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../../pkg/plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pluginpb$0 from "../../rpc/contracts/plugin/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(2618184216, name);
}

/**
 * EnablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3573057673, name);
}

/**
 * ExecPlugin runs the named plugin with the provided connection info and query.
 * Under the hood the manager spawns the binary, writes a protobuf-JSON
 * `PluginV1_ExecRequest` to stdin, and reads a `PluginV1_ExecResponse` from
 * stdout.  The `plugin` package exposes convenient aliases but the contract is
 * defined in `contracts/plugin/v1/plugin.proto`. Callers receive the structured
 * `plugin.ExecResponse` (alias for the proto type) or an error.  Historically
 * this returned a raw string; callers may need to examine the `Result` field to
 * access rows, documents, or key/value data.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} query
 * @returns {$CancellablePromise<plugin$0.ExecResponse | null>}
 */
export function ExecPlugin(name, connection, query) {
    return $Call.ByID(2332402495, name, connection, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExecTreeAction is a convenience wrapper for executing the query payload
 * attached to a tree node action.  It simply forwards to ExecPlugin.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} actionQuery
 * @returns {$CancellablePromise<plugin$0.ExecResponse | null>}
 */
export function ExecTreeAction(name, connection, actionQuery) {
    return $Call.ByID(987162126, name, connection, actionQuery).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConnectionTree asks the named plugin for its connection tree.  The
 * request contains only the connection map; the plugin defines node structure
 * and actions.  A timeout guards misbehaving plugins.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<plugin$0.ConnectionTreeResponse | null>}
 */
export function GetConnectionTree(name, connection) {
    return $Call.ByID(3147399459, name, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPluginAuthForms probes the plugin executable for supported authentication
 * forms by invoking `plugin authforms` and decoding the JSON response. If the
 * plugin doesn't implement the command or returns no forms an empty map is
 * returned.
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: plugin$0.AuthForm | null }>}
 */
export function GetPluginAuthForms(name) {
    return $Call.ByID(545463133, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListPlugins returns the discovered plugins (does not start them).
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(668942975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Rescan triggers an immediate directory scan.
 * @returns {$CancellablePromise<void>}
 */
export function Rescan() {
    return $Call.ByID(3306130489);
}

/**
 * SetApp injects the Wails application reference so the Manager can emit
 * log events to the frontend. Call this after application.New returns.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(384494566, app);
}

/**
 * Shutdown stops background scanning.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(976093531);
}

/**
 * TestConnection invokes the named plugin's `test-connection` command to verify
 * that the supplied connection parameters are valid. The plugin is expected to
 * open and ping the underlying data store without persisting anything.
 * Old plugins that do not implement the command will exit non-zero; in that
 * case TestConnection returns an error rather than a failed response so the
 * caller can distinguish "unsupported" from "tested and failed".
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<plugin$0.TestConnectionResponse | null>}
 */
export function TestConnection(name, connection) {
    return $Call.ByID(2822844201, name, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

// Private type creation functions
const $$createType0 = pluginpb$0.PluginV1_ExecResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = pluginpb$0.PluginV1_ConnectionTreeResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = pluginpb$0.PluginV1_AuthForm.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $models.PluginInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = pluginpb$0.PluginV1_TestConnectionResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
