// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Manager discovers executables under one or more plugin directories and
 * invokes them on-demand. By default the first scan location is a per-user
 * configuration directory (writable by the current user); if that path is
 * unavailable the bundled `bin/plugins` directory next to the executable is
 * used instead. Plugins found in an earlier directory mask identical names in
 * later directories. The Manager does NOT manage long-running plugin processes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../../pkg/plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pluginpb$0 from "../../rpc/contracts/plugin/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DescribeSchema asks the named plugin to provide schema metadata for the
 * given connection.  The optional database/table arguments may be empty;
 * plugins are free to ignore them.  A 30-second timeout prevents hangs.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<plugin$0.DescribeSchemaResponse | null>}
 */
export function DescribeSchema(name, connection, database, table) {
    return $Call.ByID(1218238003, name, connection, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DisablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(2618184216, name);
}

/**
 * EnablePlugin is not applicable for on-demand execution model.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3573057673, name);
}

/**
 * ExecPlugin runs the named plugin with the provided connection info, query
 * and optional options map.  Under the hood the manager spawns the binary,
 * writes a protobuf-JSON `PluginV1_ExecRequest` to stdin, and reads a
 * `PluginV1_ExecResponse` from stdout.  The `plugin` package exposes convenient
 * aliases but the contract is defined in `contracts/plugin/v1/plugin.proto`.
 * Callers receive the structured `plugin.ExecResponse` (alias for the proto
 * type) or an error.  Historically this returned a raw string; callers may need
 * to examine the `Result` field to access rows, documents, or key/value data.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} query
 * @param {{ [_ in string]?: string }} options
 * @returns {$CancellablePromise<plugin$0.ExecResponse | null>}
 */
export function ExecPlugin(name, connection, query, options) {
    return $Call.ByID(2332402495, name, connection, query, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ExecTreeAction is a convenience wrapper for executing the query payload
 * attached to a tree node action.  It simply forwards to ExecPlugin and
 * propagates any provided options map (for example "explain-query").
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} actionQuery
 * @param {{ [_ in string]?: string }} options
 * @returns {$CancellablePromise<plugin$0.ExecResponse | null>}
 */
export function ExecTreeAction(name, connection, actionQuery, options) {
    return $Call.ByID(987162126, name, connection, actionQuery, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCompletionFields asks the named plugin for discoverable field names for a
 * specific database/collection.  The call is used by the editor auto-completion
 * feature.  Plugins that don't implement the CompletionFieldsProvider interface
 * return an empty response.  A 15-second timeout guards misbehaving plugins.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {string} database
 * @param {string} collection
 * @returns {$CancellablePromise<plugin$0.GetCompletionFieldsResponse | null>}
 */
export function GetCompletionFields(name, connection, database, collection) {
    return $Call.ByID(2222067792, name, connection, database, collection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetConnectionTree asks the named plugin for its connection tree.  The
 * request contains only the connection map; the plugin defines node structure
 * and actions.  A timeout guards misbehaving plugins.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<plugin$0.ConnectionTreeResponse | null>}
 */
export function GetConnectionTree(name, connection) {
    return $Call.ByID(3147399459, name, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetPluginAuthForms probes the plugin executable for supported authentication
 * forms by invoking `plugin authforms` and decoding the JSON response. If the
 * plugin doesn't implement the command or returns no forms an empty map is
 * returned.
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: plugin$0.AuthForm | null }>}
 */
export function GetPluginAuthForms(name) {
    return $Call.ByID(545463133, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListPlugins returns the discovered plugins (does not start them).
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(668942975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * MutateRow forwards a single-row mutation request to the specified plugin.
 * The semantics of `source`, `values` and `filter` are driver-defined; the
 * core does not interpret them.  The operation type (insert/update/delete)
 * is described by the OperationType enum.  A 30-second timeout guards
 * against misbehaving plugins.
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @param {plugin$0.OperationType} operation
 * @param {string} source
 * @param {{ [_ in string]?: string }} values
 * @param {string} filter
 * @returns {$CancellablePromise<plugin$0.MutateRowResponse | null>}
 */
export function MutateRow(name, connection, operation, source, values, filter) {
    return $Call.ByID(3105031897, name, connection, operation, source, values, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * Rescan clears the plugin registry and triggers a full re-probe of the
 * plugins directory. This ensures that any metadata changes to existing
 * plugins are picked up (e.g. after a plugin update).
 * @returns {$CancellablePromise<void>}
 */
export function Rescan() {
    return $Call.ByID(3306130489);
}

/**
 * SetApp injects the Wails application reference so the Manager can emit
 * log events to the frontend. Call this after application.New returns.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(384494566, app);
}

/**
 * Shutdown is a no-op; there is no background scanner to stop.
 * It is kept so Wails can still call the lifecycle method without error.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(976093531);
}

/**
 * TestConnection invokes the named plugin's `test-connection` command to verify
 * that the supplied connection parameters are valid. The plugin is expected to
 * open and ping the underlying data store without persisting anything.
 * Old plugins that do not implement the command will exit non-zero; in that
 * case TestConnection returns an error rather than a failed response so the
 * caller can distinguish "unsupported" from "tested and failed".
 * @param {string} name
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<plugin$0.TestConnectionResponse | null>}
 */
export function TestConnection(name, connection) {
    return $Call.ByID(2822844201, name, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

// Private type creation functions
const $$createType0 = pluginpb$0.PluginV1_DescribeSchemaResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = pluginpb$0.PluginV1_ExecResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = pluginpb$0.PluginV1_GetCompletionFieldsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = pluginpb$0.PluginV1_ConnectionTreeResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = pluginpb$0.PluginV1_AuthForm.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = $models.PluginInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = pluginpb$0.PluginV1_MutateRowResponse.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = pluginpb$0.PluginV1_TestConnectionResponse.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
