// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../../pkg/plugin/models.js";

/**
 * On Windows the helper hideWindow (implemented in platform-specific files)
 * will configure subprocesses so they do not show a console window. This
 * keeps the application from flashing plugin binaries during background
 * scans or executions.
 * 
 * PluginInfo holds metadata that the UI can display for each plugin.
 * 
 * The `ID` field is used as the canonical driver identifier (also stored
 * in connection.driver_type).  It is always normalized to strip any
 * filesystem extension such as ".exe" so that the same value appears on all
 * OSes.
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["manifest_path"] = undefined;
        }
        if (!("running" in $$source)) {
            /**
             * always false in on-demand model
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * follows PluginV1.Type enum (DRIVER = 1)
             * @member
             * @type {number | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["capabilities"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {plugin$0.PermissionDecl[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {plugin$0.Limits | null | undefined}
             */
            this["limits"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {plugin$0.RuntimeSpec | null | undefined}
             */
            this["runtime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["contact"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["settings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType0;
        const $$createField18_0 = $$createType7;
        const $$createField19_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField10_0($$parsedSource["capabilities"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField11_0($$parsedSource["permissions"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField12_0($$parsedSource["limits"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField13_0($$parsedSource["runtime"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField14_0($$parsedSource["tags"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField18_0($$parsedSource["metadata"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField19_0($$parsedSource["settings"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = plugin$0.PermissionDecl.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = plugin$0.Limits.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = plugin$0.RuntimeSpec.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
