// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pluginpb$0 from "../../rpc/contracts/plugin/v1/models.js";

export const AuthForm = pluginpb$0.PluginV1_AuthForm;

/**
 * @typedef {pluginpb$0.PluginV1_AuthForm} AuthForm
 */
