// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pluginpb$0 from "../../rpc/contracts/plugin/v1/models.js";

export const AuthForm = pluginpb$0.PluginV1_AuthForm;

/**
 * @typedef {pluginpb$0.PluginV1_AuthForm} AuthForm
 */

export const ConnectionTreeResponse = pluginpb$0.PluginV1_ConnectionTreeResponse;

/**
 * @typedef {pluginpb$0.PluginV1_ConnectionTreeResponse} ConnectionTreeResponse
 */

export const DescribeSchemaResponse = pluginpb$0.PluginV1_DescribeSchemaResponse;

/**
 * @typedef {pluginpb$0.PluginV1_DescribeSchemaResponse} DescribeSchemaResponse
 */

/**
 * ExecResponse now contains a typed ExecResult which can represent SQL rows,
 * document lists, or key/value maps. Plugins should return one of those
 * payloads rather than a flat string.
 */
export const ExecResponse = pluginpb$0.PluginV1_ExecResponse;

/**
 * ExecResponse now contains a typed ExecResult which can represent SQL rows,
 * document lists, or key/value maps. Plugins should return one of those
 * payloads rather than a flat string.
 * @typedef {pluginpb$0.PluginV1_ExecResponse} ExecResponse
 */

export const GetCompletionFieldsResponse = pluginpb$0.PluginV1_GetCompletionFieldsResponse;

/**
 * @typedef {pluginpb$0.PluginV1_GetCompletionFieldsResponse} GetCompletionFieldsResponse
 */

export const MutateRowResponse = pluginpb$0.PluginV1_MutateRowResponse;

/**
 * @typedef {pluginpb$0.PluginV1_MutateRowResponse} MutateRowResponse
 */

/**
 * @typedef {pluginpb$0.PluginV1_MutateRowRequest_OperationType} OperationType
 */

export const TestConnectionResponse = pluginpb$0.PluginV1_TestConnectionResponse;

/**
 * @typedef {pluginpb$0.PluginV1_TestConnectionResponse} TestConnectionResponse
 */
